export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  CONTENT_PRODUCT_MANAGE: 'content.product.manage',
  CONTENT_NEWS_MANAGE: 'content.news.manage',
  CONTENT_MEDIA_MANAGE: 'content.media.manage',
  CONTENT_FAQ_MANAGE: 'content.faq.manage',
  CONTENT_PARTNER_MANAGE: 'content.partner.manage',
  PAGE_MANAGE: 'page.manage',
  CUSTOMER_MESSAGE_MANAGE: 'customer.message.manage',
  RECORD_LOG_VIEW: 'record.log.view',
  RECORD_MAIL_VIEW: 'record.mail.view',
  SYSTEM_ACCOUNT_MANAGE: 'system.account.manage',
  SYSTEM_ROLE_MANAGE: 'system.role.manage',
  SETTING_ENTERPRISE_MANAGE: 'setting.enterprise.manage',
  SETTING_MAIL_MANAGE: 'setting.mail.manage',
} as const;

export const PERMISSION_DEFINITIONS = [
  {
    code: PERMISSIONS.DASHBOARD_VIEW,
    name: '查看仪表盘',
    module: '仪表盘',
    description: '查看仪表盘统计与动态',
    sortOrder: 10,
  },
  {
    code: PERMISSIONS.CONTENT_PRODUCT_MANAGE,
    name: '管理产品中心',
    module: '内容管理',
    description: '维护产品中心内容',
    sortOrder: 20,
  },
  {
    code: PERMISSIONS.CONTENT_NEWS_MANAGE,
    name: '管理新闻中心',
    module: '内容管理',
    description: '维护新闻中心内容',
    sortOrder: 50,
  },
  {
    code: PERMISSIONS.CONTENT_FAQ_MANAGE,
    name: '管理常见问题',
    module: '内容管理',
    description: '维护常见问题内容',
    sortOrder: 56,
  },
  {
    code: PERMISSIONS.CONTENT_PARTNER_MANAGE,
    name: '管理合作客户',
    module: '内容管理',
    description: '维护合作客户内容',
    sortOrder: 57,
  },
  {
    code: PERMISSIONS.CONTENT_MEDIA_MANAGE,
    name: '管理多媒体库',
    module: '内容管理',
    description: '维护媒体文件与文件夹',
    sortOrder: 60,
  },
  {
    code: PERMISSIONS.PAGE_MANAGE,
    name: '管理页面配置',
    module: '页面管理',
    description: '维护官网页面配置',
    sortOrder: 70,
  },
  {
    code: PERMISSIONS.CUSTOMER_MESSAGE_MANAGE,
    name: '管理客户留言',
    module: '客户管理',
    description: '查看和处理客户留言',
    sortOrder: 80,
  },
  {
    code: PERMISSIONS.RECORD_LOG_VIEW,
    name: '查看操作日志',
    module: '操作记录',
    description: '查看后台操作日志',
    sortOrder: 90,
  },
  {
    code: PERMISSIONS.RECORD_MAIL_VIEW,
    name: '查看邮件记录',
    module: '操作记录',
    description: '查看邮件发送记录',
    sortOrder: 100,
  },
  {
    code: PERMISSIONS.SYSTEM_ACCOUNT_MANAGE,
    name: '管理账号',
    module: '系统管理',
    description: '维护后台账号',
    sortOrder: 110,
  },
  {
    code: PERMISSIONS.SYSTEM_ROLE_MANAGE,
    name: '管理角色',
    module: '系统管理',
    description: '维护角色与权限分配',
    sortOrder: 120,
  },
  {
    code: PERMISSIONS.SETTING_ENTERPRISE_MANAGE,
    name: '管理企业设置',
    module: '系统设置',
    description: '维护企业基础信息',
    sortOrder: 130,
  },
  {
    code: PERMISSIONS.SETTING_MAIL_MANAGE,
    name: '管理邮件设置',
    module: '系统设置',
    description: '维护邮件配置并发送测试邮件',
    sortOrder: 140,
  },
] as const;
